In [65]:
import pandas as pd
import numpy as np

In [66]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

df = train.copy()

In [67]:
df.columns

Index(['id', 'age', 'daily_screen_time_hours', 'social_media_hours',
       'gaming_hours', 'work_study_hours', 'sleep_hours',
       'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time',
       'gender', 'stress_level', 'academic_work_impact', 'addicted_label'],
      dtype='str')

In [68]:
print(df.shape)
print(train.shape)
print(test.shape)

(691369, 14)
(691369, 14)
(296302, 13)

In [69]:
df.describe()

,id,age,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,notifications_per_day,app_opens_per_day,weekend_screen_time,addicted_label
count,691369.000000,662440.000000,595515.000000,557374.000000,564548.000000,639851.000000,646889.000000,623785.000000,610659.000000,579306.000000,691369.000000
mean,345684.000000,26.615408,7.640865,2.471038,1.459265,2.366971,6.804334,145.894900,102.636781,9.479866,0.709424
std,199581.183467,5.153162,2.721446,1.316137,0.934552,1.258797,1.234512,65.917556,48.093970,2.856006,0.454028
min,0.000000,18.000000,0.500000,0.000000,0.000000,0.000000,4.500000,20.000000,15.000000,0.510000,0.000000
25%,172842.000000,22.000000,5.480000,1.450000,0.700000,1.360000,5.780000,93.000000,64.000000,7.280000,0.000000
50%,345684.000000,27.000000,7.770000,2.310000,1.330000,2.200000,6.800000,150.000000,104.000000,9.580000,1.000000
75%,518526.000000,31.000000,9.840000,3.370000,2.090000,3.200000,7.870000,204.000000,145.000000,11.750000,1.000000
max,691368.000000,35.000000,15.000000,8.000000,4.000000,6.000000,9.000000,250.000000,180.000000,17.560000,1.000000

In [70]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 691369 entries, 0 to 691368
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       691369 non-null  int64
 1   age                      662440 non-null  float64
 2   daily_screen_time_hours  595515 non-null  float64
 3   social_media_hours       557374 non-null  float64
 4   gaming_hours             564548 non-null  float64
 5   work_study_hours         639851 non-null  float64
 6   sleep_hours              646889 non-null  float64
 7   notifications_per_day    623785 non-null  float64
 8   app_opens_per_day        610659 non-null  float64
 9   weekend_screen_time      579306 non-null  float64
 10  gender                   662335 non-null  str
 11  stress_level             636221 non-null  str
 12  academic_work_impact     647145 non-null  str
 13  addicted_label           691369 non-null  int64
dtypes: float64(9), int64(2), str(3)
memory usage: 73.8 MB
None

In [71]:
print(df.head())

   id   age  daily_screen_time_hours  social_media_hours  gaming_hours  \
0   0  24.0                      NaN                1.83          1.59
1   1  19.0                     5.97                1.08           NaN
2   2  18.0                     5.09                 NaN           NaN
3   3  21.0                     6.42                1.26          1.42
4   4  26.0                    11.20                1.87          2.81

   work_study_hours  sleep_hours  notifications_per_day  app_opens_per_day  \
0              2.11         7.46                  122.0               38.0
1              3.03         8.22                   76.0               19.0
2               NaN         6.25                  134.0               60.0
3              3.36         8.85                  112.0               94.0
4              1.95         5.25                    NaN                NaN

   weekend_screen_time  gender stress_level academic_work_impact  \
0                 8.63    Male       Medium                   No
1                  NaN  Female       Medium                   No
2                 7.47  Female          Low                  Yes
3                 8.66   Other          Low                  NaN
4                13.39  Female       Medium                   No

   addicted_label
0               1
1               0
2               0
3               1
4               1

In [72]:
missing_count = train.isnull().sum()

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": (missing_count / len(train) * 100).round(2)
}).sort_values("missing_count", ascending=False)

display(missing_summary)

                         missing_count  missing_percentage
social_media_hours              133995               19.38
gaming_hours                    126821               18.34
weekend_screen_time             112063               16.21
daily_screen_time_hours          95854               13.86
app_opens_per_day                80710               11.67
notifications_per_day            67584                9.78
stress_level                     55148                7.98
work_study_hours                 51518                7.45
sleep_hours                      44480                6.43
academic_work_impact             44224                6.40
gender                           29034                4.20
age                              28929                4.18
id                                   0                0.00
addicted_label                       0                0.00

In [73]:
total_duplicate_rows = train.duplicated().sum()

print(f"Jumlah baris duplikat penuh: {total_duplicate_rows}")

duplicate_rows = train[train.duplicated(keep=False)].sort_values(
    by=train.columns.tolist()
)

display(duplicate_rows)

Jumlah baris duplikat penuh: 0

Empty DataFrame
Columns: [id, age, daily_screen_time_hours, social_media_hours, gaming_hours, work_study_hours, sleep_hours, notifications_per_day, app_opens_per_day, weekend_screen_time, gender, stress_level, academic_work_impact, addicted_label]
Index: []

In [74]:
unique_summary = pd.DataFrame({
    "unique_count": train.nunique(dropna=False),
    "dtype": train.dtypes.astype(str),
    "sample_values": [
        train[col].drop_duplicates().head(5).tolist()
        for col in train.columns
    ]
}).sort_values("unique_count")

display(unique_summary)

,unique_count,dtype,sample_values
addicted_label,2,int64,"[1, 0]"
academic_work_impact,3,str,"[No, Yes, nan]"
gender,4,str,"[Male, Female, Other, nan]"
stress_level,4,str,"[Medium, Low, High, nan]"
age,19,float64,"[24.0, 19.0, 18.0, 21.0, 26.0]"
app_opens_per_day,167,float64,"[38.0, 19.0, 60.0, 94.0, nan]"
notifications_per_day,232,float64,"[122.0, 76.0, 134.0, 112.0, nan]"
gaming_hours,402,float64,"[1.59, nan, 1.42, 2.81, 1.56]"
sleep_hours,452,float64,"[7.46, 8.22, 6.25, 8.85, 5.25]"
work_study_hours,601,float64,"[2.11, 3.03, nan, 3.36, 1.95]"
social_media_hours,722,float64,"[1.83, 1.08, nan, 1.26, 1.87]"
daily_screen_time_hours,1390,float64,"[nan, 5.97, 5.09, 6.42, 11.2]"
weekend_screen_time,1438,float64,"[8.63, nan, 7.47, 8.66, 13.39]"
id,691369,int64,"[0, 1, 2, 3, 4]"

In [75]:
# 1. Isi missing value semua kolom numerik dengan median,
#    kecuali stress_level, gender, addicted_label, dan id

excluded_cols = ["stress_level", "gender", "addicted_label", "id"]

median_cols = [
    col for col in train.columns
    if col not in excluded_cols and pd.api.types.is_numeric_dtype(train[col])
]

train[median_cols] = train[median_cols].fillna(train[median_cols].median())

In [76]:
# 2. Ubah gender yang missing/NaN/null menjadi kategori "other"

train["gender"] = (
    train["gender"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({"nan": pd.NA, "null": pd.NA, "": pd.NA})
    .fillna("other")
)

In [77]:
# 3. Ubah stress_level menjadi ordinal:
#    low = 0, medium = 1, high = 2

stress_mapping = {
    "low": 0,
    "medium": 1,
    "high": 2
}

train["stress_level"] = (
    train["stress_level"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({"nan": pd.NA, "null": pd.NA, "": pd.NA})
    .map(stress_mapping)
)

In [78]:
# 4. Isi stress_level yang missing dengan nilai modus

stress_mode = train["stress_level"].mode()[0]

train["stress_level"] = (
    train["stress_level"]
    .fillna(stress_mode)
    .astype(int)
)

In [79]:
# Ubah missing/NaN/null pada academic_work_impact menjadi kategori "other"

train["academic_work_impact"] = (
    train["academic_work_impact"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({"nan": pd.NA, "null": pd.NA, "": pd.NA})
    .fillna("other")
)

In [80]:
missing_count = train.isnull().sum()

missing_summary = pd.DataFrame({
    "missing_count": missing_count,
    "missing_percentage": (missing_count / len(train) * 100).round(2)
}).sort_values("missing_count", ascending=False)

display(missing_summary)

                         missing_count  missing_percentage
id                                   0                 0.0
age                                  0                 0.0
daily_screen_time_hours              0                 0.0
social_media_hours                   0                 0.0
gaming_hours                         0                 0.0
work_study_hours                     0                 0.0
sleep_hours                          0                 0.0
notifications_per_day                0                 0.0
app_opens_per_day                    0                 0.0
weekend_screen_time                  0                 0.0
gender                               0                 0.0
stress_level                         0                 0.0
academic_work_impact                 0                 0.0
addicted_label                       0                 0.0